### ISSUE TITLE
Fix the build on RDT

### ISSUE THREAD

**Issue by edevost** [edevost/foxmask#34]
I have no clue why it's not building. Build perfectly locally... Error is:

```python
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/foxmask/envs/cli/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/foxmask/envs/cli/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/foxmask/envs/cli/local/lib/python2.7/site-packages/sphinx/config.py", line 138, in __init__
    raise ConfigError(CONFIG_EXIT_ERROR)
ConfigError: The configuration file (or one of the modules it imports) called sys.exit()

Configuration error:
The configuration file (or one of the modules it imports) called sys.exit()
```

**Comment by edevost** [comment]
Cleaning the docs/conf.py was the solution. Something in the file was causing the build to fail on RDT, but was building locally...
